version: '3.8'

services:
  ai-agent:
    image: mirzaasadijaz/enterprise-ai-agent:latest
    container_name: ai-agent-container
    
    env_file:
      - .env
      
    ports:
      - "8000:8000"
      
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./chat_memory.db:/app/chat_memory.db
      
    restart: unless-stopped